name: Modifyworld
main: ru.tehkode.modifyworld.bukkit.Modifyworld
softdepend: [ LuckPerms ]
version: "${project.version}"
author: t3hk0d3
website: www.bukkit.org
description: World modification permission ruleset
api-version: '26.2'
